USB_VID = 0x239A
USB_PID = 0x802A
USB_PRODUCT = "Node nRF52840"
USB_MANUFACTURER = "RHT"

MCU_CHIP = nrf52840

QSPI_FLASH_FILESYSTEM = 0
SPI_FLASH_FILESYSTEM = 0
INTERNAL_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 0



CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_NETWORK = 0
CIRCUITPY_PS2IO = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_I2CSLAVE = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_USB_MIDI = 0